### ISSUE TITLE
Feature Request: RMINC should understand world coordinates

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#104]
Due to bug https://github.com/Mouse-Imaging-Centre/pydpiper/issues/255 RMINC barfs on masks, even though those masks are in the proper space.

If RMINC properly handled coordinates, this would be a moot point, as the mask orientation would be handled properly.

**Comment by cfhammill** [comment]
Hi Gabe,

What do you mean by barfing, what commands are failing, is the issue dimension order or something of that sort? Is this perhaps related to #103?

**Comment by gdevenyi** [comment]
It complains that the mask is the wrong size (i.e. RMINC catches the issue, doesn't throw an error), since the dimension order in the file is different.

This is unrelated to #103

**Comment by cfhammill** [comment]
What code complains?

**Comment by gdevenyi** [comment]
https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_voxel_statistics.R#L514-L521

**Comment by cfhammill** [comment]
This will likely not be fixed in the near term. Working in voxel coordinates is what allows RMINC to goes as fast as it does. A dimension order check is certainly possible to add, but the end result is that all volumes will need to be in the same dim order. There is allows weirdness for visualization if you use anything other than z-y-x

**Comment by gdevenyi** [comment]
Okay.
