### ISSUE TITLE
Feature Request: vertexFindPeaks like mincFindPeaks

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#110]
I think this may be a lot more challenging because vertex numbers aren't an indication of topology.

**Comment by cfhammill** [comment]
The code is there to make this happen, that's why I created the mesh->graph functions. Right now it can do connected components on the surface, assessing whether each vertex is higher than its n nearest neighbours is trivial. Incorporating distance though may be more challenging, but I think is well within the realm of possibility

**Comment by cfhammill** [comment]
Written, just need to make the output format a bit more like mincFindPeaks. 

As a user do you want a data frame of coordinates for the peaks as well as their index and value. Right now it outputs a set of peak indices.

**Comment by gdevenyi** [comment]
The big win is index so we can extract a peak and make a plot. The value is nice to know what the height of the peak is. There would definitely be next-level uses of coordinates but those would be less often used than the index.

**Comment by cfhammill** [comment]
Indices or a logical mask are the two output types presently. I was considering making it more similar to mincFindPeaks, but maybe because meshes are easier to keep around and query its not all that necessary. I put instructions in the doc for how to extract coords from the mesh object given the indices, maybe that's sufficient

**Comment by gdevenyi** [comment]
If it's documented, that's suffcient!
