### ISSUE TITLE
better error message when ulimit reached?

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#119]
```
> volumes <- anatGetAll(filenames = df$labels, defs = label_defs, method = "labels")
/projects/mice/share/arch/linux-3_2_0-36-generic-x86_64-eglibc-2_15/src/minc-toolkit/libminc/libsrc2/volume.c:1248 (from MINC2): Unable to open file '/hpf/largeprojects/MICe/bdarwin/2016-01-Foster/pipeline-as-twolevel/twolevel_first_level/C57BL/6_processed/FOSTER_M1023_dc/resampled/FOSTER_M1023_dc_N_I_lsq6-resampled-labels.mnc'
Error in count_labels(filenames) : basic_string::resize
```

**Comment by cfhammill** [comment]
Interestingly this is also pointing to a bug in Rccp on our system. Possibly ancient GCC related.

`Rcpp::cppFunction('void throwerr(){ stop("error here") }')()`

is throwing a string resize error instead of the expected `error here`

So at the moment with our Rcpp the internal file checks will return this string resize error instead of
helpful messages.
