### ISSUE TITLE
qMincApply registry inconsistently cleaned up?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#169]
We have noticed the following issue:
Run a mincLmer (or similar), model fails due to jobs failing or such. The qMincApply registry still exists after this.

Try and run code again, now model fails due to presence of qMincApply registry, but it appears the registry is then cleaned up during the failure handling.

Result is an error about qMincApply_registry being non-empty, but then going to check, it's gone.

Subsequent run of the same code then works, because the registry was cleaned up after the last error.

**Comment by cfhammill** [comment]
Are you running with `wait = FALSE`? Otherwise I'm a bit surprised this is happening, the cleanup gets registered with `on.exit` (https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_parallel.R#L402). This should be run even on error, but of course if cleanup or wait is FALSE it doesn't get cleaned up. Ideally it would be run even with `wait = FALSE`, but that would take some metaprogramming black magic to get the `on.exit` run in the parent environment with knowledge of the registry (from the child environment).

**Comment by gdevenyi** [comment]
I don't think I am, where would I find that?

This is second hand reporting so, one other possibility is that the process was interrupted with the "stop" button. Would cleanup happen then?

**Comment by cfhammill** [comment]
It should happen in the case of ESC/CTRL-C/stop, although perhaps if the escape is executed many times rapidly it could interrupt the cleanup code as well. Not sure...

**Comment by gdevenyi** [comment]
Probably hitting the button a bunch of times.

My more careful testing shows it does clean up properly.
