### ISSUE TITLE
mincLogLikRatio fails with nested random effects fails

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#209]
```R
 mincLogLikRatio(mod_cub_coh_sex,mod_cub_coh_sex_nested)
mincLogLikRatio output
Model 1 :
  Formula:  abs_jac ~ ns(age, 3) * new_groups + sex + (1 | mouse) + (1 | 
    cohort)
Model 2 :
  Formula:  abs_jac ~ ns(age, 3) * new_groups + sex + (1 | cohort/mouse)
Mask used:  /data/chamal/projects/elisa/maternal_infection/nov30_twolevel/votedmask.mnc 
Chi-squared Degrees of Freedom: 0 
```

The 0 degrees of freedom is (probably?) wrong, and the mincFDR of this gives NaN everywhere.

Not clear where things are going wrong. Visualization of the shiny results shows everything looks fine.

**Comment by cfhammill** [comment]
if each mouse is only in a single cohort I suspect that those two models are actually the same.

**Comment by gdevenyi** [comment]
This study has 19 cohorts with 3-6 mice per cohort.

As I understand the multi-level modelling, nesting the mice random effects inside the cohort is intended to group the random effects at cohort level and vary the mice within them.

I was basing this on my reading of:
https://stats.stackexchange.com/questions/228800/crossed-vs-nested-random-effects-how-do-they-differ-and-how-are-they-specified

**Comment by cfhammill** [comment]
The zero df is probably before they have the same number of parameters. The nesting unique-ifies mice names so that mouse3cohort1 is treated differently than mouse3cohort2. If all of your mouse names are unique already (1 | mouse) + (1 | cohort) == (1 | mouse/cohort) == (1 | cohort/mouse).

**Comment by jasonlerch** [comment]
What happens if you run that log likelihood test outside of RMINC? I.e.

m1 <- lmer(value ~ covariates + (1|mouse) + (1|cohort))
m2 <- lmer(value ~ covariates + (1|cohort/mouse))
anova(m1,m2)

Jason

On Apr 10, 2018, 12:03 PM -0400, Chris Hammill <notifications@github.com>, wrote:

The zero df is probably before they have the same number of parameters. The nesting unique-ifies mice names so that mouse3cohort1 is treated differently than mouse3cohort2. If all of your mouse names are unique already (1 | mouse) + (1 | cohort) == (1 | mouse/cohort) == (1 | cohort/mouse).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mouse-2DImaging-2DCentre_RMINC_issues_209-23issuecomment-2D380155744&d=DwMFaQ&c=Sj806OTFwmuG2UO1EEDr-2uZRzm2EPz39TfVBG2Km-o&r=HeHbjTJnvHS1LfU-oVbj4xp56MzXc8SwpgPYe318jo0&m=JTRJH-WOUcdQZOo_ZjXSSmBRk47fxVWtSE1V6mglz1o&s=3FbvbtitTjwhOvSgxmVZlIwF0K7Yu6BXAZ9T9Be9IJU&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAxd-5F-2DACTaJbJhH7xKZU7MSMp-2DRqLKMTks5tnNfKgaJpZM4TKl5p&d=DwMFaQ&c=Sj806OTFwmuG2UO1EEDr-2uZRzm2EPz39TfVBG2Km-o&r=HeHbjTJnvHS1LfU-oVbj4xp56MzXc8SwpgPYe318jo0&m=JTRJH-WOUcdQZOo_ZjXSSmBRk47fxVWtSE1V6mglz1o&s=PyuMVGt1dA9fO6jfKOF86W9jHYzxfxWDH0o2x_9cCog&e=>.

________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.

**Comment by gdevenyi** [comment]
Closing this for now, turns on the student was not using the proper id columns for their data so all testing is null and void.
