### ISSUE TITLE
Feature Request: Post-hoc tests on {minc,anat,vertex}{lm,lmer}?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#245]
We are now regularly running into the case where we have more than 2 group levels in a given model.

I know I can get a different comparison if I change the reference level and re-run the model, but as I understand it, that is a multiple comparison so the statistical significance is is incorrect. The way I would do this with a regular lm is the multicomp glht function.

**Comment by cfhammill** [comment]
Not `stats::TukeyHSD`? 

I suppose we could return the vcov matrix for each voxel, but that would be very space inefficient. Is there something holding you back from: 

```r
pMincApply(files, function(v, data) glht(lm(v ~ ..., data = data)), data = frame)`
```

**Comment by gdevenyi** [comment]
Tukey is probably okay as well? Not sure it can do lmers

**Comment by gdevenyi** [comment]
Re: holding back, yes, not knowing I can do that :)

**Comment by cfhammill** [comment]
I don't think I'm going to implement this feature. If another dev is willing and able I'd be happy to coach, but right now most of my energy is going toward building/scaling bayesian approaches. Improving docs so that people are more comfortable writing their own parallelized voxel level code is probably a much better use of time.
