### ISSUE TITLE
mincLm fails with too many open files

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#61]
Running mincLm on the Foster dataset causes a crash on the 1042nd (?!) file:

```
> abs_voxel_fits <- mincLm(abs_jacobians ~ sex, data=csv)
Method: lm
Number of volumes: 1055
/projects/mice/share/arch/linux-3_2_0-36-generic-x86_64-eglibc-2_15/src/minc-toolkit/libminc/libsrc2/volume.c:1248 (from MINC2): Unable to open file '/hpf/largeprojects/MICe/bdarwin/2016-01-Foster//pipeline/build-model-jan27_processed/FOSTER_M1048_dc/stats-volumes/FOSTER_M1048_dc-final-nlin_with_additional_inverted_absolute_log_determinant_fwhm0.1.mnc'
Error in mincLm(abs_jacobians ~ sex, data = csv) : 
  Error opening input file: /hpf/largeprojects/MICe/bdarwin/2016-01-Foster//pipeline/build-model-jan27_processed/FOSTER_M1048_dc/stats-volumes/FOSTER_M1048_dc-final-nlin_with_additional_inverted_absolute_log_determinant_fwhm0.1.mnc.
> 
```

At this point the R process is basically nonfunctional.  `lsof -p <pid>` shows it has 1023 regular files open...coincidentally, `ulimit -Sn` gives 1024 on this machine...

**Comment by jasonlerch** [comment]
Does altering ulimit -Sn get around the problem?

**Comment by bcdarwin** [comment]
That was my workaround.  You could imaging checking whether there's sufficient fds available, but I guess the real problem is that the handles are just leaked silently and never get gc'd (compare just opening 5000 files in pure R).

**Comment by bcdarwin** [comment]
Also, you don't get a nice message that you've run out of connections, you're just unable to open the files (or any files...ever).

**Comment by jasonlerch** [comment]
There must be a systems call portable across platforms to get the soft and hard limits for open connections - so at the very least we could check whether the total number of files in a mincLm (and friends) call exceeds that and refuse to run.

**Comment by cfhammill** [comment]
A couple of ideas: 
Mac can report ulimit -Sn, so we can call out and check if that minus the number of open files is greater than the number of minc files before running.

We can open and close the minc file descriptors repeatedly throughout the C  code, Ben did a back of the envelope calculation putting it at an extra minute or two for 1000 minc files with 500 slices on the dimension mincLm reads along. This could be used in combination with the earlier strategy, engaging slow mode if there are too many files.

Lastly we could provide an experiment abstraction for large collections of minc files. We could dump all of the voxel values into sqlite table along with necessary metadata. Since dplyr can lazily [manipulate databases](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html), many of our common operations can be reformulated as dplyr operations. The table would be filled iteratively, closing each minc file after writing to the db. We would then only need one file descriptor to access the database.

**Comment by vfonov** [comment]
you can also concatenate multiple minc files into a single 4D minc file, and have only one file open. 

That would require rewriting the minc reading code though.

**Comment by cfhammill** [comment]
Yes, that is another alternative, Ben and I had discussed it briefly last week, but we got sidetracked with wondering about meta-data. Re-working the code to support 4D files, possibly as a special case at first doesn't seem unmanageable.

**Comment by cfhammill** [comment]
@bcdarwin, can you retry this when you get a chance (without setting ulimit) this should fail with an error like "unable to open N files, not enough file descriptors, try setting ulimit -Sn to some larger number"
