### ISSUE TITLE
Performance Improvement? qMincMask files could be generated in the cluster job instead of prior to job submission?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#92]
If I have a very large number of jobs because I can fill my cluster, I have to wait a very long time before jobs are actually submitted in BatchJobs.

**Comment by cfhammill** [comment]
Hi Gabe,

This problem is due to trying to support SciNet, which may be more trouble than it's worth. Maybe you have a solution - BatchJobs ships single jobs only, but in order to use all 8 cores of a SciNet node the job is further subdivided into 8 multicore jobs. Our current strategy for parallelizing jobs is to label the masked voxels 1:N and have each job work only on its given number, this strategy breaks down with the subdivision, and so a mask for each job needs to be generated prior to submitting the jobs. If there was a way to submit atomic jobs on scinet, only a single mask would need to be generated and this problem would disappear (not to mention simplifying many other irritating parts of this code). 

I could probably hack in a way to have the jobs themselves generate the masks, but it would be nicer to solve the underlying problem

**Comment by gdevenyi** [comment]
Right, scinet issues, it's always a big hassle to special-case scinet sadly.

Could there be perhaps a "spin up" component of the scinet job that creates the mask, prior to launching the multicore job?

What I'm really thinking of is using R's variable methods to divide up the data, then creating the masks in the jobs from that info. Not sure how sane that is, I'm still very much an R newbie.

**Comment by cfhammill** [comment]
I'm starting to think I will special-case the nested parallelism it will make everything else a lot cleaner and remove the mask writing bottleneck.
